
version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: neotech-frontend

    ports:
      - "5173:5173"

    env_file:
      - ./frontend/.env

    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: neotech-backend

    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
